-- tests/media/test_media_directives.lua
-- Tests for GAP-037 through GAP-043: Media and Presentation Features

local ws_parser = require("whisker.parser.ws_parser")

describe("Media Directive Parsing", function()
  local parser

  before_each(function()
    parser = ws_parser.new()
  end)

  -- GAP-037: Audio Embedding
  describe("Audio Embedding (GAP-037)", function()
    it("should parse basic @audio directive", function()
      local result = parser:parse_passage_content('@audio("background.mp3")')
      assert.is_not_nil(result)
      assert.equals("passage_content", result.type)
      assert.equals(1, #result.nodes)
      assert.equals("audio", result.nodes[1].type)
      assert.equals("background.mp3", result.nodes[1].src)
    end)

    it("should parse @audio with single quotes", function()
      local result = parser:parse_passage_content("@audio('effect.wav')")
      assert.is_not_nil(result)
      assert.equals("audio", result.nodes[1].type)
      assert.equals("effect.wav", result.nodes[1].src)
    end)

    it("should parse @audio with autoplay attribute", function()
      local result = parser:parse_passage_content('@audio("music.ogg", autoplay: true)')
      assert.is_not_nil(result)
      assert.equals("audio", result.nodes[1].type)
      assert.is_true(result.nodes[1].autoplay)
    end)

    it("should parse @audio with loop attribute", function()
      local result = parser:parse_passage_content('@audio("ambient.mp3", loop: true)')
      assert.is_not_nil(result)
      assert.is_true(result.nodes[1].loop)
    end)

    it("should parse @audio with controls=false", function()
      local result = parser:parse_passage_content('@audio("hidden.mp3", controls: false)')
      assert.is_not_nil(result)
      assert.is_false(result.nodes[1].controls)
    end)

    it("should default controls to true", function()
      local result = parser:parse_passage_content('@audio("file.mp3")')
      assert.is_not_nil(result)
      assert.is_true(result.nodes[1].controls)
    end)

    it("should parse @audio with volume attribute", function()
      local result = parser:parse_passage_content('@audio("quiet.mp3", volume: 0.5)')
      assert.is_not_nil(result)
      assert.equals(0.5, result.nodes[1].volume)
    end)

    it("should parse @audio with multiple attributes", function()
      local result = parser:parse_passage_content('@audio("bgm.mp3", autoplay: true, loop: true, volume: 0.8)')
      assert.is_not_nil(result)
      assert.is_true(result.nodes[1].autoplay)
      assert.is_true(result.nodes[1].loop)
      assert.equals(0.8, result.nodes[1].volume)
    end)

    it("should parse @audio with muted attribute", function()
      local result = parser:parse_passage_content('@audio("video.mp3", muted: true)')
      assert.is_not_nil(result)
      assert.is_true(result.nodes[1].muted)
    end)
  end)

  -- GAP-038: Video Embedding
  describe("Video Embedding (GAP-038)", function()
    it("should parse basic @video directive", function()
      local result = parser:parse_passage_content('@video("intro.mp4")')
      assert.is_not_nil(result)
      assert.equals("video", result.nodes[1].type)
      assert.equals("intro.mp4", result.nodes[1].src)
    end)

    it("should parse @video with width and height", function()
      local result = parser:parse_passage_content('@video("scene.webm", width: 640, height: 480)')
      assert.is_not_nil(result)
      assert.equals(640, result.nodes[1].width)
      assert.equals(480, result.nodes[1].height)
    end)

    it("should parse @video with autoplay, loop, muted", function()
      local result = parser:parse_passage_content('@video("trailer.mp4", autoplay: true, loop: true, muted: true)')
      assert.is_not_nil(result)
      assert.is_true(result.nodes[1].autoplay)
      assert.is_true(result.nodes[1].loop)
      assert.is_true(result.nodes[1].muted)
    end)

    it("should parse @video with controls attribute", function()
      local result = parser:parse_passage_content('@video("movie.mp4", controls: false)')
      assert.is_not_nil(result)
      assert.is_false(result.nodes[1].controls)
    end)

    it("should default video controls to true", function()
      local result = parser:parse_passage_content('@video("file.mp4")')
      assert.is_not_nil(result)
      assert.is_true(result.nodes[1].controls)
    end)

    it("should parse @video with poster attribute", function()
      local result = parser:parse_passage_content('@video("clip.mp4", poster: "thumbnail.jpg")')
      assert.is_not_nil(result)
      assert.equals("thumbnail.jpg", result.nodes[1].poster)
    end)
  end)

  -- GAP-039: Generic Embeds
  describe("Generic Embeds (GAP-039)", function()
    it("should parse basic @embed directive", function()
      local result = parser:parse_passage_content('@embed("https://example.com/widget")')
      assert.is_not_nil(result)
      assert.equals("embed", result.nodes[1].type)
      assert.equals("https://example.com/widget", result.nodes[1].url)
    end)

    it("should parse @embed with dimensions", function()
      local result = parser:parse_passage_content('@embed("https://youtube.com/embed/VIDEO_ID", width: 560, height: 315)')
      assert.is_not_nil(result)
      assert.equals(560, result.nodes[1].width)
      assert.equals(315, result.nodes[1].height)
    end)

    it("should default embed dimensions", function()
      local result = parser:parse_passage_content('@embed("https://example.com")')
      assert.is_not_nil(result)
      assert.equals(560, result.nodes[1].width)
      assert.equals(315, result.nodes[1].height)
    end)

    it("should default sandbox to true", function()
      local result = parser:parse_passage_content('@embed("https://example.com")')
      assert.is_not_nil(result)
      assert.is_true(result.nodes[1].sandbox)
    end)

    it("should parse @embed with sandbox=false", function()
      local result = parser:parse_passage_content('@embed("https://trusted.com", sandbox: false)')
      assert.is_not_nil(result)
      assert.is_false(result.nodes[1].sandbox)
    end)

    it("should parse @embed with title attribute", function()
      local result = parser:parse_passage_content('@embed("https://example.com", title: "My Widget")')
      assert.is_not_nil(result)
      assert.equals("My Widget", result.nodes[1].title)
    end)

    it("should default title to 'Embedded content'", function()
      local result = parser:parse_passage_content('@embed("https://example.com")')
      assert.is_not_nil(result)
      assert.equals("Embedded content", result.nodes[1].title)
    end)

    it("should parse @embed with loading attribute", function()
      local result = parser:parse_passage_content('@embed("https://example.com", loading: eager)')
      assert.is_not_nil(result)
      assert.equals("eager", result.nodes[1].loading)
    end)

    it("should default loading to lazy", function()
      local result = parser:parse_passage_content('@embed("https://example.com")')
      assert.is_not_nil(result)
      assert.equals("lazy", result.nodes[1].loading)
    end)
  end)

  -- GAP-043: Media Attributes for Images
  describe("Media Attributes (GAP-043)", function()
    it("should parse markdown image with width and height", function()
      local result = parser:parse_passage_content('![Alt](image.jpg width=400 height=300)')
      assert.is_not_nil(result)
      assert.equals("image", result.nodes[1].type)
      assert.equals(400, result.nodes[1].width)
      assert.equals(300, result.nodes[1].height)
    end)

    it("should parse markdown image with loading attribute", function()
      local result = parser:parse_passage_content('![Alt](big.jpg loading=lazy)')
      assert.is_not_nil(result)
      assert.equals("lazy", result.nodes[1].loading)
    end)

    it("should parse markdown image with class attribute", function()
      local result = parser:parse_passage_content('![Alt](photo.jpg class=hero-image)')
      assert.is_not_nil(result)
      assert.equals("hero-image", result.nodes[1].class)
    end)

    it("should parse markdown image with id attribute", function()
      local result = parser:parse_passage_content('![Alt](image.jpg id=main-image)')
      assert.is_not_nil(result)
      assert.equals("main-image", result.nodes[1].id)
    end)

    it("should parse markdown image with title and attributes", function()
      local result = parser:parse_passage_content('![Alt](image.jpg "Title" width=200)')
      assert.is_not_nil(result)
      assert.equals("Title", result.nodes[1].title)
      assert.equals(200, result.nodes[1].width)
    end)

    it("should parse @image directive with attributes", function()
      local result = parser:parse_passage_content('@image("photo.png", width: 100, height: 100, loading: lazy)')
      assert.is_not_nil(result)
      assert.equals("image", result.nodes[1].type)
      assert.equals(100, result.nodes[1].width)
      assert.equals(100, result.nodes[1].height)
      assert.equals("lazy", result.nodes[1].loading)
    end)
  end)
end)
