--- Plugin Lifecycle Tests
-- @module tests.unit.plugin.plugin_lifecycle_spec

describe("PluginLifecycle", function()
  local PluginLifecycle

  before_each(function()
    package.loaded["whisker.plugin.plugin_lifecycle"] = nil
    PluginLifecycle = require("whisker.plugin.plugin_lifecycle")
  end)

  describe("State validation", function()
    it("should recognize valid states", function()
      assert.is_true(PluginLifecycle.is_valid_state("discovered"))
      assert.is_true(PluginLifecycle.is_valid_state("loaded"))
      assert.is_true(PluginLifecycle.is_valid_state("initialized"))
      assert.is_true(PluginLifecycle.is_valid_state("enabled"))
      assert.is_true(PluginLifecycle.is_valid_state("disabled"))
      assert.is_true(PluginLifecycle.is_valid_state("destroyed"))
      assert.is_true(PluginLifecycle.is_valid_state("error"))
    end)

    it("should reject invalid states", function()
      assert.is_false(PluginLifecycle.is_valid_state("invalid"))
      assert.is_false(PluginLifecycle.is_valid_state(""))
      assert.is_false(PluginLifecycle.is_valid_state(nil))
    end)
  end)

  describe("Transition validation", function()
    it("should allow valid transitions from discovered", function()
      assert.is_true(PluginLifecycle.is_valid_transition("discovered", "loaded"))
      assert.is_true(PluginLifecycle.is_valid_transition("discovered", "error"))
    end)

    it("should allow valid transitions from loaded", function()
      assert.is_true(PluginLifecycle.is_valid_transition("loaded", "initialized"))
      assert.is_true(PluginLifecycle.is_valid_transition("loaded", "error"))
    end)

    it("should allow valid transitions from initialized", function()
      assert.is_true(PluginLifecycle.is_valid_transition("initialized", "enabled"))
      assert.is_true(PluginLifecycle.is_valid_transition("initialized", "error"))
    end)

    it("should allow valid transitions from enabled", function()
      assert.is_true(PluginLifecycle.is_valid_transition("enabled", "disabled"))
      assert.is_true(PluginLifecycle.is_valid_transition("enabled", "error"))
    end)

    it("should allow valid transitions from disabled", function()
      assert.is_true(PluginLifecycle.is_valid_transition("disabled", "enabled"))
      assert.is_true(PluginLifecycle.is_valid_transition("disabled", "destroyed"))
      assert.is_true(PluginLifecycle.is_valid_transition("disabled", "error"))
    end)

    it("should allow error to destroyed transition", function()
      assert.is_true(PluginLifecycle.is_valid_transition("error", "destroyed"))
    end)

    it("should reject invalid transitions", function()
      assert.is_false(PluginLifecycle.is_valid_transition("loaded", "enabled"))
      assert.is_false(PluginLifecycle.is_valid_transition("destroyed", "enabled"))
      assert.is_false(PluginLifecycle.is_valid_transition("destroyed", "loaded"))
      assert.is_false(PluginLifecycle.is_valid_transition("enabled", "loaded"))
    end)

    it("should reject transitions from destroyed (terminal state)", function()
      assert.is_false(PluginLifecycle.is_valid_transition("destroyed", "discovered"))
      assert.is_false(PluginLifecycle.is_valid_transition("destroyed", "error"))
    end)
  end)

  describe("get_allowed_transitions", function()
    it("should return allowed transitions for each state", function()
      local discovered_transitions = PluginLifecycle.get_allowed_transitions("discovered")
      assert.is_table(discovered_transitions)
      assert.equals(2, #discovered_transitions)

      local destroyed_transitions = PluginLifecycle.get_allowed_transitions("destroyed")
      assert.is_table(destroyed_transitions)
      assert.equals(0, #destroyed_transitions)
    end)

    it("should return empty table for unknown state", function()
      local transitions = PluginLifecycle.get_allowed_transitions("unknown")
      assert.is_table(transitions)
      assert.equals(0, #transitions)
    end)
  end)

  describe("get_transition_hooks", function()
    it("should return on_load and on_init for loaded to initialized", function()
      local hooks = PluginLifecycle.get_transition_hooks("loaded", "initialized")
      assert.is_table(hooks)
      assert.equals(2, #hooks)
      assert.equals("on_load", hooks[1])
      assert.equals("on_init", hooks[2])
    end)

    it("should return on_enable for initialized to enabled", function()
      local hooks = PluginLifecycle.get_transition_hooks("initialized", "enabled")
      assert.is_table(hooks)
      assert.equals(1, #hooks)
      assert.equals("on_enable", hooks[1])
    end)

    it("should return on_disable for enabled to disabled", function()
      local hooks = PluginLifecycle.get_transition_hooks("enabled", "disabled")
      assert.is_table(hooks)
      assert.equals(1, #hooks)
      assert.equals("on_disable", hooks[1])
    end)

    it("should return on_destroy for disabled to destroyed", function()
      local hooks = PluginLifecycle.get_transition_hooks("disabled", "destroyed")
      assert.is_table(hooks)
      assert.equals(1, #hooks)
      assert.equals("on_destroy", hooks[1])
    end)

    it("should return nil for transitions without hooks", function()
      local hooks = PluginLifecycle.get_transition_hooks("discovered", "loaded")
      assert.is_nil(hooks)
    end)
  end)

  describe("is_terminal_state", function()
    it("should identify destroyed as terminal", function()
      assert.is_true(PluginLifecycle.is_terminal_state("destroyed"))
    end)

    it("should not identify other states as terminal", function()
      assert.is_false(PluginLifecycle.is_terminal_state("discovered"))
      assert.is_false(PluginLifecycle.is_terminal_state("loaded"))
      assert.is_false(PluginLifecycle.is_terminal_state("enabled"))
      assert.is_false(PluginLifecycle.is_terminal_state("error"))
    end)
  end)

  describe("is_active_state", function()
    it("should identify enabled as active", function()
      assert.is_true(PluginLifecycle.is_active_state("enabled"))
    end)

    it("should not identify other states as active", function()
      assert.is_false(PluginLifecycle.is_active_state("discovered"))
      assert.is_false(PluginLifecycle.is_active_state("loaded"))
      assert.is_false(PluginLifecycle.is_active_state("disabled"))
    end)
  end)

  describe("get_transition_path", function()
    it("should return empty path for same state", function()
      local path = PluginLifecycle.get_transition_path("enabled", "enabled")
      assert.is_table(path)
      assert.equals(0, #path)
    end)

    it("should find direct transition", function()
      local path = PluginLifecycle.get_transition_path("discovered", "loaded")
      assert.is_table(path)
      assert.equals(1, #path)
      assert.equals("loaded", path[1])
    end)

    it("should find multi-step path", function()
      local path = PluginLifecycle.get_transition_path("loaded", "enabled")
      assert.is_table(path)
      assert.equals(2, #path)
      assert.equals("initialized", path[1])
      assert.equals("enabled", path[2])
    end)

    it("should return nil for impossible path", function()
      local path = PluginLifecycle.get_transition_path("destroyed", "enabled")
      assert.is_nil(path)
    end)
  end)

  describe("State machine", function()
    it("should create state machine with default state", function()
      local machine = PluginLifecycle.create_state_machine()
      assert.equals("discovered", machine:get_state())
    end)

    it("should create state machine with initial state", function()
      local machine = PluginLifecycle.create_state_machine("loaded")
      assert.equals("loaded", machine:get_state())
    end)

    it("should allow valid transitions", function()
      local machine = PluginLifecycle.create_state_machine("loaded")
      local success, err = machine:transition("initialized")
      assert.is_true(success)
      assert.is_nil(err)
      assert.equals("initialized", machine:get_state())
    end)

    it("should reject invalid transitions", function()
      local machine = PluginLifecycle.create_state_machine("loaded")
      local success, err = machine:transition("enabled")
      assert.is_false(success)
      assert.is_string(err)
      assert.equals("loaded", machine:get_state())
    end)

    it("should track transition history", function()
      local machine = PluginLifecycle.create_state_machine("loaded")
      machine:transition("initialized")
      machine:transition("enabled")

      local history = machine:get_history()
      assert.equals(2, #history)
      assert.equals("loaded", history[1].from)
      assert.equals("initialized", history[1].to)
      assert.equals("initialized", history[2].from)
      assert.equals("enabled", history[2].to)
    end)

    it("should store error message in error state", function()
      local machine = PluginLifecycle.create_state_machine("loaded")
      machine:transition("error", "Test error message")

      assert.equals("error", machine:get_state())
      assert.equals("Test error message", machine:get_error())
    end)

    it("should check if can transition", function()
      local machine = PluginLifecycle.create_state_machine("loaded")
      assert.is_true(machine:can_transition("initialized"))
      assert.is_false(machine:can_transition("enabled"))
    end)

    it("should get allowed next states", function()
      local machine = PluginLifecycle.create_state_machine("disabled")
      local allowed = machine:get_allowed_next()
      assert.is_table(allowed)
      assert.equals(3, #allowed)  -- enabled, destroyed, error
    end)
  end)
end)
