-- tests/core/test_module_parser.lua
-- Tests for module system parsing (INCLUDE, FUNCTION, NAMESPACE)

local WSParser = require("lib.whisker.parser.ws_parser")

describe("Module System Parsing", function()

  describe("INCLUDE Declaration", function()
    it("should parse INCLUDE with double-quoted path", function()
      local parser = WSParser.new()
      local result = parser:parse_include('INCLUDE "utils/helpers.ws"')
      assert.is_not_nil(result)
      assert.equals("include_declaration", result.type)
      assert.equals("utils/helpers.ws", result.path)
    end)

    it("should parse INCLUDE with single-quoted path", function()
      local parser = WSParser.new()
      local result = parser:parse_include("INCLUDE 'lib/common.ws'")
      assert.is_not_nil(result)
      assert.equals("lib/common.ws", result.path)
    end)

    it("should parse INCLUDE with nested path", function()
      local parser = WSParser.new()
      local result = parser:parse_include('INCLUDE "modules/game/combat.ws"')
      assert.is_not_nil(result)
      assert.equals("modules/game/combat.ws", result.path)
    end)

    it("should return nil for invalid INCLUDE", function()
      local parser = WSParser.new()
      local result, err = parser:parse_include('INCLUDE invalid')
      assert.is_nil(result)
      assert.is_not_nil(err)
    end)
  end)

  describe("FUNCTION Declaration", function()
    it("should parse FUNCTION with no parameters", function()
      local parser = WSParser.new()
      local result = parser:parse_function_declaration("FUNCTION greet()\nHello world\nEND")
      assert.is_not_nil(result)
      assert.equals("function_declaration", result.type)
      assert.equals("greet", result.name)
      assert.equals(0, #result.params)
    end)

    it("should parse FUNCTION with single parameter", function()
      local parser = WSParser.new()
      local result = parser:parse_function_declaration("FUNCTION sayHello(name)\nHello, $name!\nEND")
      assert.is_not_nil(result)
      assert.equals("sayHello", result.name)
      assert.equals(1, #result.params)
      assert.equals("name", result.params[1].name)
    end)

    it("should parse FUNCTION with multiple parameters", function()
      local parser = WSParser.new()
      local result = parser:parse_function_declaration("FUNCTION calculate(a, b, c)\nResult\nEND")
      assert.is_not_nil(result)
      assert.equals("calculate", result.name)
      assert.equals(3, #result.params)
      assert.equals("a", result.params[1].name)
      assert.equals("b", result.params[2].name)
      assert.equals("c", result.params[3].name)
    end)

    it("should return nil for invalid FUNCTION", function()
      local parser = WSParser.new()
      local result, err = parser:parse_function_declaration("FUNCTION\nEND")
      assert.is_nil(result)
      assert.is_not_nil(err)
    end)
  end)

  describe("NAMESPACE Declaration", function()
    it("should parse NAMESPACE block", function()
      local parser = WSParser.new()
      local result = parser:parse_namespace_declaration("NAMESPACE Combat\nContent\nEND")
      assert.is_not_nil(result)
      assert.equals("namespace_declaration", result.type)
      assert.equals("Combat", result.name)
    end)

    it("should return nil for invalid NAMESPACE", function()
      local parser = WSParser.new()
      local result, err = parser:parse_namespace_declaration("NAMESPACE\nEND")
      assert.is_nil(result)
      assert.is_not_nil(err)
    end)
  end)

  describe("RETURN Statement", function()
    it("should parse RETURN with value", function()
      local parser = WSParser.new()
      local result = parser:parse_return("RETURN 42")
      assert.is_not_nil(result)
      assert.equals("return_statement", result.type)
      assert.equals("42", result.value)
    end)

    it("should parse RETURN with expression", function()
      local parser = WSParser.new()
      local result = parser:parse_return("RETURN $a + $b")
      assert.is_not_nil(result)
      assert.equals("$a + $b", result.value)
    end)

    it("should return nil for invalid RETURN", function()
      local parser = WSParser.new()
      local result, err = parser:parse_return("NOTRETURN value")
      assert.is_nil(result)
      assert.is_not_nil(err)
    end)
  end)

  describe("Module Keyword Detection", function()
    it("should detect INCLUDE keyword", function()
      local parser = WSParser.new()
      assert.is_true(parser:is_module_keyword('INCLUDE "path"'))
    end)

    it("should detect FUNCTION keyword", function()
      local parser = WSParser.new()
      assert.is_true(parser:is_module_keyword("FUNCTION name()"))
    end)

    it("should detect NAMESPACE keyword", function()
      local parser = WSParser.new()
      assert.is_true(parser:is_module_keyword("NAMESPACE Name"))
    end)

    it("should detect END keyword", function()
      local parser = WSParser.new()
      assert.is_true(parser:is_module_keyword("END"))
      assert.is_true(parser:is_module_keyword("END NAMESPACE"))
    end)

    it("should detect RETURN keyword", function()
      local parser = WSParser.new()
      assert.is_true(parser:is_module_keyword("RETURN value"))
    end)

    it("should not detect regular content", function()
      local parser = WSParser.new()
      assert.is_false(parser:is_module_keyword("Hello world"))
      assert.is_false(parser:is_module_keyword("Some text"))
    end)
  end)

end)
