--- SugarCube expression parser unit tests
-- Tests expression and condition parsing
--
-- tests/unit/twine/formats/sugarcube/expression_parser_spec.lua

describe("ExpressionParser", function()
  local ExpressionParser

  before_each(function()
    package.loaded['whisker.twine.formats.sugarcube.expression_parser'] = nil
    ExpressionParser = require('whisker.twine.formats.sugarcube.expression_parser')
  end)

  describe("parse", function()
    describe("literals", function()
      it("parses integer numbers", function()
        local ast = ExpressionParser.parse("42")
        assert.equals("literal", ast.type)
        assert.equals("number", ast.literal_type)
        assert.equals(42, ast.value)
      end)

      it("parses negative numbers", function()
        local ast = ExpressionParser.parse("-10")
        assert.equals("literal", ast.type)
        assert.equals(-10, ast.value)
      end)

      it("parses decimal numbers", function()
        local ast = ExpressionParser.parse("3.14")
        assert.equals("literal", ast.type)
        assert.equals(3.14, ast.value)
      end)

      it("parses double-quoted strings", function()
        local ast = ExpressionParser.parse('"hello"')
        assert.equals("literal", ast.type)
        assert.equals("string", ast.literal_type)
        assert.equals("hello", ast.value)
      end)

      it("parses single-quoted strings", function()
        local ast = ExpressionParser.parse("'world'")
        assert.equals("literal", ast.type)
        assert.equals("world", ast.value)
      end)

      it("parses true boolean", function()
        local ast = ExpressionParser.parse("true")
        assert.equals("literal", ast.type)
        assert.equals("boolean", ast.literal_type)
        assert.equals(true, ast.value)
      end)

      it("parses false boolean", function()
        local ast = ExpressionParser.parse("false")
        assert.equals("literal", ast.type)
        assert.equals(false, ast.value)
      end)

      it("parses null as nil", function()
        local ast = ExpressionParser.parse("null")
        assert.equals("literal", ast.type)
        assert.equals("nil", ast.literal_type)
      end)
    end)

    describe("variables", function()
      it("parses $variable", function()
        local ast = ExpressionParser.parse("$gold")
        assert.equals("variable", ast.type)
        assert.equals("gold", ast.name)
      end)

      it("parses _temporary variable", function()
        local ast = ExpressionParser.parse("_temp")
        assert.equals("variable", ast.type)
        assert.equals("temp", ast.name)
      end)

      it("parses variable with underscore in name", function()
        local ast = ExpressionParser.parse("$player_health")
        assert.equals("variable", ast.type)
        assert.equals("player_health", ast.name)
      end)
    end)

    describe("property access", function()
      it("parses $obj.prop", function()
        local ast = ExpressionParser.parse("$player.health")
        assert.equals("property_access", ast.type)
        assert.equals("variable", ast.target.type)
        assert.equals("player", ast.target.name)
        assert.equals("health", ast.property)
      end)
    end)

    describe("array access", function()
      it("parses $arr[0]", function()
        local ast = ExpressionParser.parse("$inventory[0]")
        assert.equals("array_access", ast.type)
        assert.equals("variable", ast.target.type)
        assert.equals("inventory", ast.target.name)
        -- Index should be 1 (Lua-adjusted)
        assert.equals(1, ast.index.value)
      end)
    end)

    describe("array literals", function()
      it("parses empty array", function()
        local ast = ExpressionParser.parse("[]")
        assert.equals("array_literal", ast.type)
        assert.equals(0, #ast.items)
      end)

      it("parses array with numbers", function()
        local ast = ExpressionParser.parse("[1, 2, 3]")
        assert.equals("array_literal", ast.type)
        assert.equals(3, #ast.items)
        assert.equals(1, ast.items[1].value)
        assert.equals(2, ast.items[2].value)
        assert.equals(3, ast.items[3].value)
      end)

      it("parses array with strings", function()
        local ast = ExpressionParser.parse('["sword", "shield"]')
        assert.equals("array_literal", ast.type)
        assert.equals(2, #ast.items)
        assert.equals("sword", ast.items[1].value)
        assert.equals("shield", ast.items[2].value)
      end)
    end)

    describe("binary operations", function()
      it("parses addition", function()
        local ast = ExpressionParser.parse("$a + 10")
        assert.equals("binary_op", ast.type)
        assert.equals("+", ast.operator)
      end)

      it("parses subtraction", function()
        local ast = ExpressionParser.parse("$health - 5")
        assert.equals("binary_op", ast.type)
        assert.equals("-", ast.operator)
      end)

      it("parses multiplication", function()
        local ast = ExpressionParser.parse("$x * 2")
        assert.equals("binary_op", ast.type)
        assert.equals("*", ast.operator)
      end)

      it("parses division", function()
        local ast = ExpressionParser.parse("$total / 4")
        assert.equals("binary_op", ast.type)
        assert.equals("/", ast.operator)
      end)
    end)
  end)

  describe("parse_condition", function()
    describe("comparison operators", function()
      it("parses greater than", function()
        local ast = ExpressionParser.parse_condition("$gold > 50")
        assert.equals("binary_op", ast.type)
        assert.equals(">", ast.operator)
      end)

      it("parses less than", function()
        local ast = ExpressionParser.parse_condition("$health < 25")
        assert.equals("binary_op", ast.type)
        assert.equals("<", ast.operator)
      end)

      it("parses greater than or equal", function()
        local ast = ExpressionParser.parse_condition("$level >= 10")
        assert.equals("binary_op", ast.type)
        assert.equals(">=", ast.operator)
      end)

      it("parses less than or equal", function()
        local ast = ExpressionParser.parse_condition("$stamina <= 0")
        assert.equals("binary_op", ast.type)
        assert.equals("<=", ast.operator)
      end)

      it("parses equality", function()
        local ast = ExpressionParser.parse_condition("$status == 'active'")
        assert.equals("binary_op", ast.type)
        assert.equals("==", ast.operator)
      end)

      it("parses inequality", function()
        local ast = ExpressionParser.parse_condition("$name != 'Bob'")
        assert.equals("binary_op", ast.type)
        assert.equals("!=", ast.operator)
      end)

      it("normalizes === to ==", function()
        local ast = ExpressionParser.parse_condition("$x === 5")
        assert.equals("binary_op", ast.type)
        assert.equals("==", ast.operator)
      end)

      it("normalizes !== to !=", function()
        local ast = ExpressionParser.parse_condition("$y !== 0")
        assert.equals("binary_op", ast.type)
        assert.equals("!=", ast.operator)
      end)
    end)

    describe("SugarCube aliases", function()
      it("parses 'is' as ==", function()
        local ast = ExpressionParser.parse_condition("$name is 'Alice'")
        assert.equals("binary_op", ast.type)
        assert.equals("==", ast.operator)
      end)

      it("parses 'eq' as ==", function()
        local ast = ExpressionParser.parse_condition("$count eq 10")
        assert.equals("binary_op", ast.type)
        assert.equals("==", ast.operator)
      end)

      it("parses 'neq' as !=", function()
        local ast = ExpressionParser.parse_condition("$value neq 0")
        assert.equals("binary_op", ast.type)
        assert.equals("!=", ast.operator)
      end)

      it("parses 'gt' as >", function()
        local ast = ExpressionParser.parse_condition("$score gt 100")
        assert.equals("binary_op", ast.type)
        assert.equals(">", ast.operator)
      end)

      it("parses 'gte' as >=", function()
        local ast = ExpressionParser.parse_condition("$level gte 5")
        assert.equals("binary_op", ast.type)
        assert.equals(">=", ast.operator)
      end)

      it("parses 'lt' as <", function()
        local ast = ExpressionParser.parse_condition("$health lt 10")
        assert.equals("binary_op", ast.type)
        assert.equals("<", ast.operator)
      end)

      it("parses 'lte' as <=", function()
        local ast = ExpressionParser.parse_condition("$mana lte 0")
        assert.equals("binary_op", ast.type)
        assert.equals("<=", ast.operator)
      end)
    end)

    describe("logical operators", function()
      it("parses 'and'", function()
        local ast = ExpressionParser.parse_condition("$hasKey and $doorLocked")
        assert.equals("logical_op", ast.type)
        assert.equals("and", ast.operator)
      end)

      it("parses 'or'", function()
        local ast = ExpressionParser.parse_condition("$isAdmin or $isOwner")
        assert.equals("logical_op", ast.type)
        assert.equals("or", ast.operator)
      end)

      it("parses '&&' as and", function()
        local ast = ExpressionParser.parse_condition("$a && $b")
        assert.equals("logical_op", ast.type)
        assert.equals("and", ast.operator)
      end)

      it("parses '||' as or", function()
        local ast = ExpressionParser.parse_condition("$x || $y")
        assert.equals("logical_op", ast.type)
        assert.equals("or", ast.operator)
      end)
    end)

    describe("not operator", function()
      it("parses 'not'", function()
        local ast = ExpressionParser.parse_condition("not $flag")
        assert.equals("unary_op", ast.type)
        assert.equals("not", ast.operator)
      end)

      it("parses '!'", function()
        local ast = ExpressionParser.parse_condition("!$active")
        assert.equals("unary_op", ast.type)
        assert.equals("not", ast.operator)
      end)
    end)

    describe("complex conditions", function()
      it("handles comparison with logical", function()
        local ast = ExpressionParser.parse_condition("$gold > 50 and $hasMap")
        assert.equals("logical_op", ast.type)
        assert.equals("and", ast.operator)
      end)

      it("handles variable as boolean", function()
        local ast = ExpressionParser.parse_condition("$isReady")
        assert.equals("variable", ast.type)
        assert.equals("isReady", ast.name)
      end)
    end)
  end)
end)
