local helper = require("tests.test_helper")
local parser = require("whisker.format.parsers.sugarcube")

describe("SugarCube Inventory System", function()
  local story_content
  local parsed

  setup(function()
    story_content = helper.load_fixture("sugarcube/inventory_test.twee")
    parsed = parser.parse(story_content)
  end)

  it("should parse StoryInit passage", function()
    local init = helper.find_passage(parsed, "StoryInit")
    assert.is_not_nil(init)
  end)

  it("should parse set macro", function()
    local init = helper.find_passage(parsed, "StoryInit")
    assert.matches("<<set", init.content)
  end)

  it("should parse object literal", function()
    local init = helper.find_passage(parsed, "StoryInit")
    assert.matches("%$items to {", init.content)
  end)

  it("should parse nested object properties", function()
    local init = helper.find_passage(parsed, "StoryInit")
    assert.matches("name:", init.content)
    assert.matches("price:", init.content)
    assert.matches("type:", init.content)
  end)

  it("should parse for range loop", function()
    local shop = helper.find_passage(parsed, "Shop")
    assert.is_not_nil(shop)
    assert.matches("<<for _itemKey, _item range", shop.content)
  end)

  it("should parse temporary variables", function()
    local shop = helper.find_passage(parsed, "Shop")
    assert.is_not_nil(shop)
    assert.matches("_itemKey", shop.content)
    assert.matches("_item", shop.content)
  end)

  it("should parse capture macro", function()
    local shop = helper.find_passage(parsed, "Shop")
    assert.is_not_nil(shop)
    assert.matches("<<capture", shop.content)
  end)

  it("should parse link macro", function()
    local shop = helper.find_passage(parsed, "Shop")
    assert.is_not_nil(shop)
    assert.matches("<<link", shop.content)
  end)

  it("should parse if macro", function()
    local shop = helper.find_passage(parsed, "Shop")
    assert.is_not_nil(shop)
    assert.matches("<<if", shop.content)
  end)

  it("should parse closing tags", function()
    local shop = helper.find_passage(parsed, "Shop")
    assert.is_not_nil(shop)
    assert.matches("<<capture", shop.content)
    assert.matches("<</capture>>", shop.content)
    assert.matches("<<link", shop.content)
    assert.matches("<</link>>", shop.content)
  end)

  it("should parse array push method", function()
    local shop = helper.find_passage(parsed, "Shop")
    assert.is_not_nil(shop)
    assert.matches("%$inventory%.push%(", shop.content)
  end)

  it("should parse compound assignment", function()
    local shop = helper.find_passage(parsed, "Shop")
    assert.is_not_nil(shop)
    assert.matches("%$gold %-%=", shop.content)
  end)

  it("should parse property access", function()
    local shop = helper.find_passage(parsed, "Shop")
    assert.is_not_nil(shop)
    assert.matches("_item%.price", shop.content)
  end)
end)
